# Generated by Django 4.2.3 on 2023-08-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'пользователь с таким e-mail адресом уже существует'}, max_length=254, unique=True, verbose_name='e-mail'),
        ),
    ]
