# Generated by Django 4.2.3 on 2023-08-09 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('genre_name', models.CharField(max_length=100, unique=True, verbose_name='название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='название книги')),
                ('authors', models.CharField(blank=True, max_length=200, null=True, verbose_name='авторы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('language', models.CharField(blank=True, max_length=100, null=True, verbose_name='язык')),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='год публикации')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='время добавления')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='участие в запросе')),
                ('photo', models.ImageField(blank=True, upload_to='book_photo/', verbose_name='фотография книги')),
                ('genre', models.ManyToManyField(blank=True, related_name='books', to='books.genre')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
    ]
