# Generated by Django 4.2.3 on 2023-08-10 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('status', models.CharField(choices=[('ОП', 'Ожидание подтверждения'), ('ЗП', 'Запрос принят'), ('ДОС', 'Детали обмена согласованы'), ('ОЗ', 'Обмен завершён'), ('Откл', 'Отклонён'), ('Отм', 'Отменён')], default='ОП', max_length=100)),
                ('requester_approval', models.BooleanField(verbose_name='Одобрить Получение')),
                ('requested_part_approval', models.BooleanField(verbose_name='Одобрить Выдачу')),
                ('requester_is_changed', models.BooleanField(verbose_name='Получение Изменен')),
                ('requested_part_is_changed', models.BooleanField(verbose_name='Выдача Изменен')),
                ('requested_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_parts', to='books.book', verbose_name='Выдаваемая Книга')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested', to='books.book', verbose_name='Получаемая Книга')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказ',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('messege', models.CharField(max_length=500, verbose_name='Сообщение')),
                ('owner_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель сообщения')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чат',
            },
        ),
    ]
