# Generated by Django 4.2.3 on 2023-07-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='название жанра'),
        ),
    ]
