# Generated by Django 4.2.3 on 2023-08-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='участие в запросе'),
        ),
    ]
